# Generated by Django 5.1.15 on 2026-07-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mfadevice_onetimetoken_recoverycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
