# Generated by Django 5.1.15 on 2026-07-15 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0005_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_type', models.CharField(choices=[('internal', 'Internal'), ('ean', 'EAN'), ('gtin', 'GTIN'), ('supplier', 'Supplier')], max_length=20)),
                ('value', models.CharField(max_length=64)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['product', 'code_type', 'value'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'code_type', 'value'), name='uniq_productcode_tenant_type_value_active'), models.UniqueConstraint(condition=models.Q(('is_principal', True)), fields=('tenant', 'product', 'code_type'), name='uniq_productcode_principal_per_type')],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_units', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'ordering': ['product', 'unit'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'unit'), name='uniq_productunit_tenant_product_unit'), models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='productunit_factor_positive')],
            },
        ),
    ]
