# Generated by Django 5.2.16 on 2026-07-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalog_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
