# Generated by Django 5.1.15 on 2026-07-21 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchasereceipt_purchasereceiptitem'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Concluída'), ('failed', 'Falha')], default='completed', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='purchasing.purchaseorder')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Concluída'), ('failed', 'Falha')], default='completed', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='purchasing.purchasereceipt')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='completed', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchasing.purchasereceipt')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='purchasing.purchaseorderitem')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.supplierreturn')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
