# Generated by Django 5.2.16 on 2026-07-21 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('purchasing', '0004_recurring_po_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_profiles', to='people.person'),
        ),
    ]
