FROM node:20-bookworm

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV NPM_CONFIG_STRICT_SSL=false

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm config set strict-ssl false && npm ci

RUN ./node_modules/.bin/playwright install chromium

COPY . .

EXPOSE 5173
