# Generated by Django 5.2.16 on 2026-07-18 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_sprint7_fiscal_models'),
        ('sales', '0001_initial'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('QUEUED', 'Na fila'), ('PROCESSING', 'Processando'), ('CONCLUDED', 'Concluído'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado'), ('FAILED', 'Falha técnica')], default='PENDING', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_document_id', models.CharField(blank=True, default='', max_length=100)),
                ('cfop', models.CharField(default='5102', max_length=4)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('xml_key', models.CharField(blank=True, default='', max_length=255)),
                ('protocol', models.CharField(blank=True, default='', max_length=60)),
                ('pdf_key', models.CharField(blank=True, default='', max_length=255)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='sales.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sale',), name='unique_active_fiscal_document_per_sale'), models.UniqueConstraint(fields=('tenant', 'sale', 'attempt_number'), name='unique_attempt_per_sale')],
            },
        ),
        migrations.CreateModel(
            name='FiscalEmitter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='plugnotas', max_length=30)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('ie', models.CharField(blank=True, default='', max_length=20)),
                ('registration_source', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automatizado')], default='manual', max_length=20)),
                ('registered_at_provider', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_emitters', to='tenancy.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'branch', 'provider'), name='uniq_active_fiscal_emitter_provider_branch')],
            },
        ),
        migrations.CreateModel(
            name='FiscalProductConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cst_icms', models.CharField(blank=True, default='', max_length=4)),
                ('cst_pis', models.CharField(blank=True, default='', max_length=4)),
                ('cst_cofins', models.CharField(blank=True, default='', max_length=4)),
                ('aliquota_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('origem', models.CharField(blank=True, default='0', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_configs', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'fiscal product configs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'product'), name='uniq_active_fiscal_product_config')],
            },
        ),
    ]
