# Generated by Django 5.1.15 on 2026-07-21 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_sprint7_fiscal_models'),
        ('purchasing', '0003_purchaseordercancellation_and_more'),
        ('sales', '0003_add_return_refund_cancellation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='direction',
            field=models.CharField(choices=[('OUTPUT', 'Saída'), ('INPUT', 'Entrada')], default='OUTPUT', max_length=10),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='purchasing.purchasereceipt'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='sales.sale'),
        ),
    ]
