# Generated by Django 5.1.15 on 2026-07-16 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('warehouse', 'Armazém'), ('store', 'Loja'), ('counter', 'Balcão'), ('general', 'Geral')], default='general', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='tenancy.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['branch', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'code'), name='uniq_stocklocation_branch_code'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_active', True)), fields=('tenant', 'branch'), name='uniq_primary_location_per_branch')],
            },
        ),
    ]
