# Generated by Django 5.1.15 on 2026-07-16 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalog_rls'),
        ('inventory', '0002_stocklot'),
        ('tenancy', '0005_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('receipt', 'Entrada'), ('issue', 'Saída'), ('adjustment', 'Ajuste'), ('transfer', 'Transferência'), ('reversal', 'Reversão')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklocation')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.stocklot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.unit')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockoperation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOperationReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('original_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockoperation')),
                ('reversal_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_of', to='inventory.stockoperation')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reserved', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.stocklocation')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.stocklot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['product', 'location', 'lot'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'location', 'lot'), name='uniq_stockbalance_tenant_product_location_lot')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'idempotency_key'), name='uniq_stockoperation_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='stockoperationreversal',
            constraint=models.UniqueConstraint(fields=('tenant', 'original_operation'), name='uniq_stockoperationreversal_original'),
        ),
    ]
