# Generated by Django 5.1.15 on 2026-07-17 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockoperation_stockmovement_stockoperationreversal_and_more'),
        ('tenancy', '0005_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbalance',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockoperationreversal',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Armazem'), ('store', 'Loja'), ('counter', 'Balcao'), ('general', 'Geral')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='direction',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Saida')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='operation_type',
            field=models.CharField(choices=[('receipt', 'Entrada'), ('issue', 'Saida'), ('adjustment', 'Ajuste'), ('transfer', 'Transferencia'), ('reversal', 'Reversao')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('reversed', 'Revertida')], default='draft', max_length=20),
        ),
    ]
