# Generated by Codex on 2026-07-17

from django.db import migrations, models


RLS_TABLES = [
    'inventory_stocklocation',
    'inventory_stocklot',
    'inventory_stockoperation',
    'inventory_stockmovement',
    'inventory_stockbalance',
    'inventory_stockoperationreversal',
]


def enable_inventory_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RLS_TABLES:
            policy = f'{table}_tenant_isolation'
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(
                f'''
                CREATE POLICY "{policy}" ON "{table}"
                USING (
                    tenant_id::text = current_setting('app.current_tenant_id', true)
                    AND current_setting('app.current_tenant_id', true) <> ''
                )
                WITH CHECK (
                    tenant_id::text = current_setting('app.current_tenant_id', true)
                    AND current_setting('app.current_tenant_id', true) <> ''
                )
                '''
            )


def disable_inventory_rls(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(RLS_TABLES):
            policy = f'{table}_tenant_isolation'
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" NO FORCE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockbalance_version_stocklocation_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoperation',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(enable_inventory_rls, disable_inventory_rls),
    ]
