# Generated by Django 5.2.16 on 2026-07-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Abertura'), ('sale_payment', 'Pagamento de venda'), ('cash_in', 'Reforco'), ('cash_out', 'Sangria'), ('expense', 'Despesa'), ('other_in', 'Outra entrada'), ('other_out', 'Outra saida'), ('closing_adjustment', 'Ajuste de fechamento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('card_external', 'Cartao externo'), ('card_integrated', 'Cartao integrado'), ('card_debit', 'Cartao debito'), ('card_credit', 'Cartao credito')], max_length=30),
        ),
    ]
