# Generated by Django 5.1.15 on 2026-07-21 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_cashmovement_movement_type_and_more'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('card_external', 'Cartao externo')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.salereturn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.salereturn')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='draft', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='sales.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'idempotency_key'), name='uniq_salecancellation_tenant_idempotency')],
            },
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'idempotency_key'), name='uniq_salereturn_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='salerefund',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'idempotency_key'), name='uniq_salerefund_tenant_idempotency'),
        ),
    ]
