# Generated by Django 5.2.16 on 2026-07-21 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0004_sale_customer'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizada'), ('captured', 'Capturada'), ('cancelled', 'Cancelada'), ('failed', 'Falhou'), ('refunded', 'Estornada')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='sales.sale')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('provider_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intents', to='payments.paymentproviderconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReconciliationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado')], default='draft', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('authorization', 'Autorização'), ('capture', 'Captura'), ('cancel', 'Cancelamento'), ('refund', 'Estorno')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('succeeded', 'Sucesso'), ('failed', 'Falhou')], default='succeeded', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('provider_reference', models.CharField(max_length=100)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentintent')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_reference', models.CharField(max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('matched', 'Conciliado'), ('divergent', 'Divergente')], default='matched', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.paymentreconciliationbatch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentproviderconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'provider'), name='uniq_active_payment_provider_tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_payment_intent_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__gt', '')), fields=('tenant', 'provider_reference'), name='uniq_payment_intent_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider_reference'), name='uniq_payment_transaction_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationitem',
            constraint=models.UniqueConstraint(fields=('batch', 'provider_reference'), name='uniq_reconciliation_item_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'external_id'), name='uniq_payment_webhook_event'),
        ),
    ]
