# Generated by Django 5.2.16 on 2026-07-21 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('tenancy', '0007_sprint7_fiscal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('forecast', 'Previsto'), ('realized', 'Realizado')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['effective_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('cash', 'Caixa'), ('bank', 'Banco'), ('clearing', 'Compensação')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('partially_settled', 'Parcialmente liquidado'), ('settled', 'Liquidado'), ('cancelled', 'Cancelado')], default='pending', max_length=24)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settled_on', models.DateField()),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_adjustment', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-settled_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='tenancy.branch'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_payable_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_payable_idempotency_tenant'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_entries', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_entries', to='financial.financialaccount'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='financial.financialaccount'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='financial.payable'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='financial.receivable'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_financial_account_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cashflowentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_cashflow_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashflowentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_cashflow_idempotency_tenant'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_receivable_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_receivable_idempotency_tenant'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_settlement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payable__isnull', False), ('receivable__isnull', True)), models.Q(('payable__isnull', True), ('receivable__isnull', False)), _connector='OR'), name='financial_settlement_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_settlement_idempotency_tenant'),
        ),
    ]
