# Generated by Django 5.2.16 on 2026-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_cashflowentry_financialaccount_receivable_settlement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partially_settled', 'Parcialmente liquidado'), ('settled', 'Liquidado'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('written_off', 'Baixado')], default='pending', max_length=20),
        ),
    ]
