# Generated by Django 5.1.15 on 2026-07-15 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_branch_tenant_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMFAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_totp', models.BooleanField(default=True)),
                ('allow_email', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_policy', to='tenancy.tenant')),
            ],
        ),
    ]
