# Generated by Django 5.2.16 on 2026-07-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branch',
            name='ie',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='ie',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual'),
        ),
    ]
